package com.giovanni.contest_test;

import java.io.Serializable;
import java.util.Date;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Agent implements Serializable {

	static final long serialVersionUID = 1L;

	private String agentNumber;
	private String clientNumber;
	private String agentType;
	private String licenceNumber;
	private Date appointedDate;
	private Date terminatedDate;
	private String leaderNumber;
	private String officeCode;
	private Date licenceExpiryDate;
	private String agentMobilephone1;
	private String agentMobilephone2;
	private String agentMobilephone3;
	private String agentEmailAddress;
	private Date timeStamp;
	// private String agentCode;
	private String agentName;

	public Agent() {
	}

	public String getAgentNumber() {
		return agentNumber;
	}

	public void setAgentNumber(String agentNumber) {
		this.agentNumber = agentNumber;
	}

	public String getClientNumber() {
		return clientNumber;
	}

	public void setClientNumber(String clientNumber) {
		this.clientNumber = clientNumber;
	}

	public String getAgentType() {
		return agentType;
	}

	public void setAgentType(String agentType) {
		this.agentType = agentType;
	}

	public String getLicenceNumber() {
		return licenceNumber;
	}

	public void setLicenceNumber(String licenceNumber) {
		this.licenceNumber = licenceNumber;
	}

	public Date getAppointedDate() {
		return appointedDate;
	}

	public void setAppointedDate(Date appointedDate) {
		this.appointedDate = appointedDate;
	}

	public Date getTerminatedDate() {
		return terminatedDate;
	}

	public void setTerminatedDate(Date terminatedDate) {
		this.terminatedDate = terminatedDate;
	}

	public String getLeaderNumber() {
		return leaderNumber;
	}

	public void setLeaderNumber(String leaderNumber) {
		this.leaderNumber = leaderNumber;
	}

	public String getOfficeCode() {
		return officeCode;
	}

	public void setOfficeCode(String officeCode) {
		this.officeCode = officeCode;
	}

	public Date getLicenceExpiryDate() {
		return licenceExpiryDate;
	}

	public void setLicenceExpiryDate(Date licenceExpiryDate) {
		this.licenceExpiryDate = licenceExpiryDate;
	}

	public String getAgentMobilephone1() {
		return agentMobilephone1;
	}

	public void setAgentMobilephone1(String agentMobilephone1) {
		this.agentMobilephone1 = agentMobilephone1;
	}

	public String getAgentMobilephone2() {
		return agentMobilephone2;
	}

	public void setAgentMobilephone2(String agentMobilephone2) {
		this.agentMobilephone2 = agentMobilephone2;
	}

	public String getAgentMobilephone3() {
		return agentMobilephone3;
	}

	public void setAgentMobilephone3(String agentMobilephone3) {
		this.agentMobilephone3 = agentMobilephone3;
	}

	public String getAgentEmailAddress() {
		return agentEmailAddress;
	}

	public void setAgentEmailAddress(String agentEmailAddress) {
		this.agentEmailAddress = agentEmailAddress;
	}

	public Date getTimeStamp() {
		return timeStamp;
	}

	public void setTimeStamp(Date timeStamp) {
		this.timeStamp = timeStamp;
	}

	// public String getAgentCode() {
	// return this.agentCode;
	// }
	//
	// public void setAgentCode(String agentCode) {
	// this.agentCode = agentCode;
	// }

	public String getAgentName() {
		return this.agentName;
	}

	public void setAgentName(String agentName) {
		this.agentName = agentName;
	}
}