package com.giovanni.contest_test;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ContestDetail implements Serializable {

	static final long serialVersionUID = 1L;

	private String contestCode;
	private String policyNo;
	private String agentNumber;
	private BigDecimal api;
	private BigDecimal ape;

	public ContestDetail() {
	}

	public ContestDetail(String contestCode, String policyNo, String agentNumber) {
		this.contestCode = contestCode;
		this.policyNo = policyNo;
		this.agentNumber = agentNumber;
	}

	public String getContestCode() {
		return this.contestCode;
	}

	public void setContestCode(String contestCode) {
		this.contestCode = contestCode;
	}

	public String getPolicyNo() {
		return this.policyNo;
	}

	public void setPolicyNo(String policyNo) {
		this.policyNo = policyNo;
	}

	public String getAgentNumber() {
		return this.agentNumber;
	}

	public void setAgentNumber(String agentNumber) {
		this.agentNumber = agentNumber;
	}

	public BigDecimal getApi() {
		return api;
	}

	public void setApi(BigDecimal api) {
		this.api = api;
	}

	public BigDecimal getApe() {
		return ape;
	}

	public void setApe(BigDecimal ape) {
		this.ape = ape;
	}
}