package com.giovanni.contest_test;

import java.io.Serializable;
import java.util.Date;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ContestMaster implements Serializable {

	static final long serialVersionUID = 1L;

	private String contestCode;
	private String contestName;
	private String channel;
	private Date startDate;
	private Date endDate;
	private String contestType;
	private String contestParent;
	private String contestScript;
	private String flyersFileName;
	private String reviewingFlag;
	private Date reviewingEndDate;
	private Date timeStamp;

	public ContestMaster() {
	}

	public String getContestCode() {
		return contestCode;
	}

	public void setContestCode(String contestCode) {
		this.contestCode = contestCode;
	}

	public String getContestName() {
		return contestName;
	}

	public void setContestName(String contestName) {
		this.contestName = contestName;
	}

	public String getChannel() {
		return channel;
	}

	public void setChannel(String channel) {
		this.channel = channel;
	}

	public Date getStartDate() {
		return startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public String getContestType() {
		return contestType;
	}

	public void setContestType(String contestType) {
		this.contestType = contestType;
	}

	public String getContestParent() {
		return contestParent;
	}

	public void setContestParent(String contestParent) {
		this.contestParent = contestParent;
	}

	public String getContestScript() {
		return contestScript;
	}

	public void setContestScript(String contestScript) {
		this.contestScript = contestScript;
	}

	public String getFlyersFileName() {
		return flyersFileName;
	}

	public void setFlyersFileName(String flyersFileName) {
		this.flyersFileName = flyersFileName;
	}

	public String getReviewingFlag() {
		return reviewingFlag;
	}

	public void setReviewingFlag(String reviewingFlag) {
		this.reviewingFlag = reviewingFlag;
	}

	public Date getReviewingEndDate() {
		return reviewingEndDate;
	}

	public void setReviewingEndDate(Date reviewingEndDate) {
		this.reviewingEndDate = reviewingEndDate;
	}

	public Date getTimeStamp() {
		return timeStamp;
	}

	public void setTimeStamp(Date timeStamp) {
		this.timeStamp = timeStamp;
	}
}