package com.giovanni.contest_test;

import java.io.Serializable;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ContestParameter implements Serializable {

	static final long serialVersionUID = 1L;

	private String contestCode;
	private String paramCode;
	private String operator;
	private String value;

	public ContestParameter() {
	}

	public String getContestCode() {
		return contestCode;
	}

	public void setContestCode(String contestCode) {
		this.contestCode = contestCode;
	}

	public String getParamCode() {
		return paramCode;
	}

	public void setParamCode(String paramCode) {
		this.paramCode = paramCode;
	}

	public String getOperator() {
		return operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	public String getValue() {
		return value;
	}

	public void setValue(String value) {
		this.value = value;
	}
}