package com.giovanni.contest_test;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Policy implements Serializable {

	static final long serialVersionUID = 1L;

	private String policyNo;
	private String productCode;
	private String policyStatus;
	private String ownerNumber;
	private String payorNumber;
	private String despatchNumber;
	private String agentNumber;
	private String currency;
	private String billingFrequently;
	private String billingChannel;
	private Date originalCommencementDay;
	private Date billToDate;
	private Date paidToDate;
	private BigDecimal installmentPremium;
	private String premiumStatusCode;
	private BigDecimal outstandingAmount;
	private Date statusMovementDate;
	private BigDecimal fpdPremium;
	private Date policyDeliveryDate;
	private Date clientReceivedDate;
	private Date proposalDate;
	private Date proposalReceivedDate;
	private Date policyIssuedDate;
	private Date uwDesicionDate;
	private Date firstIssueDate;
	private String reasonCode;
	private String reffAgentCode;
	private String reffAgentName;
	private String reffOfficeCode;
	private String reffAreaCode;
	private Date effectiveDate;
	private String proposalNumber;
	private String syariahFlag;
	private Date timeStamp;
	private String agentCode;
	private String policyType;

	public Policy() {
	}

	public Policy(String policyNo, String productCode, String policyStatus, String ownerNumber, String payorNumber,
			String despatchNumber, String agentNumber, String currency, String billingFrequently, String billingChannel,
			Date originalCommencementDay, Date billToDate, Date paidToDate, BigDecimal installmentPremium,
			String premiumStatusCode, BigDecimal outstandingAmount, Date statusMovementDate, BigDecimal fpdPremium,
			Date policyDeliveryDate, Date clientReceivedDate, Date proposalDate, Date proposalReceivedDate,
			Date policyIssuedDate, Date uwDesicionDate, Date firstIssueDate, String reasonCode, String reffAgentCode,
			String reffAgentName, String reffOfficeCode, String reffAreaCode, Date effectiveDate, String proposalNumber,
			String syariahFlag, Date timeStamp, String agentCode, String policyType) {
		this.policyNo = policyNo;
		this.productCode = productCode;
		this.policyStatus = policyStatus;
		this.ownerNumber = ownerNumber;
		this.payorNumber = payorNumber;
		this.despatchNumber = despatchNumber;
		this.agentNumber = agentNumber;
		this.currency = currency;
		this.billingFrequently = billingFrequently;
		this.billingChannel = billingChannel;
		this.originalCommencementDay = originalCommencementDay;
		this.billToDate = billToDate;
		this.paidToDate = paidToDate;
		this.installmentPremium = installmentPremium;
		this.premiumStatusCode = premiumStatusCode;
		this.outstandingAmount = outstandingAmount;
		this.statusMovementDate = statusMovementDate;
		this.fpdPremium = fpdPremium;
		this.policyDeliveryDate = policyDeliveryDate;
		this.clientReceivedDate = clientReceivedDate;
		this.proposalDate = proposalDate;
		this.proposalReceivedDate = proposalReceivedDate;
		this.policyIssuedDate = policyIssuedDate;
		this.uwDesicionDate = uwDesicionDate;
		this.firstIssueDate = firstIssueDate;
		this.reasonCode = reasonCode;
		this.reffAgentCode = reffAgentCode;
		this.reffAgentName = reffAgentName;
		this.reffOfficeCode = reffOfficeCode;
		this.reffAreaCode = reffAreaCode;
		this.effectiveDate = effectiveDate;
		this.proposalNumber = proposalNumber;
		this.syariahFlag = syariahFlag;
		this.timeStamp = timeStamp;
		this.agentCode = agentCode;
		this.policyType = policyType;
	}

	public String getPolicyNo() {
		return policyNo;
	}

	public void setPolicyNo(String policyNo) {
		this.policyNo = policyNo;
	}

	public String getProductCode() {
		return productCode;
	}

	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}

	public String getPolicyStatus() {
		return policyStatus;
	}

	public void setPolicyStatus(String policyStatus) {
		this.policyStatus = policyStatus;
	}

	public String getOwnerNumber() {
		return ownerNumber;
	}

	public void setOwnerNumber(String ownerNumber) {
		this.ownerNumber = ownerNumber;
	}

	public String getPayorNumber() {
		return payorNumber;
	}

	public void setPayorNumber(String payorNumber) {
		this.payorNumber = payorNumber;
	}

	public String getDespatchNumber() {
		return despatchNumber;
	}

	public void setDespatchNumber(String despatchNumber) {
		this.despatchNumber = despatchNumber;
	}

	public String getAgentNumber() {
		return agentNumber;
	}

	public void setAgentNumber(String agentNumber) {
		this.agentNumber = agentNumber;
	}

	public String getCurrency() {
		return currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	public String getBillingFrequently() {
		return billingFrequently;
	}

	public void setBillingFrequently(String billingFrequently) {
		this.billingFrequently = billingFrequently;
	}

	public String getBillingChannel() {
		return billingChannel;
	}

	public void setBillingChannel(String billingChannel) {
		this.billingChannel = billingChannel;
	}

	public Date getOriginalCommencementDay() {
		return originalCommencementDay;
	}

	public void setOriginalCommencementDay(Date originalCommencementDay) {
		this.originalCommencementDay = originalCommencementDay;
	}

	public Date getBillToDate() {
		return billToDate;
	}

	public void setBillToDate(Date billToDate) {
		this.billToDate = billToDate;
	}

	public Date getPaidToDate() {
		return paidToDate;
	}

	public void setPaidToDate(Date paidToDate) {
		this.paidToDate = paidToDate;
	}

	public BigDecimal getInstallmentPremium() {
		return installmentPremium;
	}

	public void setInstallmentPremium(BigDecimal installmentPremium) {
		this.installmentPremium = installmentPremium;
	}

	public String getPremiumStatusCode() {
		return premiumStatusCode;
	}

	public void setPremiumStatusCode(String premiumStatusCode) {
		this.premiumStatusCode = premiumStatusCode;
	}

	public BigDecimal getOutstandingAmount() {
		return outstandingAmount;
	}

	public void setOutstandingAmount(BigDecimal outstandingAmount) {
		this.outstandingAmount = outstandingAmount;
	}

	public Date getStatusMovementDate() {
		return statusMovementDate;
	}

	public void setStatusMovementDate(Date statusMovementDate) {
		this.statusMovementDate = statusMovementDate;
	}

	public BigDecimal getFpdPremium() {
		return fpdPremium;
	}

	public void setFpdPremium(BigDecimal fpdPremium) {
		this.fpdPremium = fpdPremium;
	}

	public Date getPolicyDeliveryDate() {
		return policyDeliveryDate;
	}

	public void setPolicyDeliveryDate(Date policyDeliveryDate) {
		this.policyDeliveryDate = policyDeliveryDate;
	}

	public Date getClientReceivedDate() {
		return clientReceivedDate;
	}

	public void setClientReceivedDate(Date clientReceivedDate) {
		this.clientReceivedDate = clientReceivedDate;
	}

	public Date getProposalDate() {
		return proposalDate;
	}

	public void setProposalDate(Date proposalDate) {
		this.proposalDate = proposalDate;
	}

	public Date getProposalReceivedDate() {
		return proposalReceivedDate;
	}

	public void setProposalReceivedDate(Date proposalReceivedDate) {
		this.proposalReceivedDate = proposalReceivedDate;
	}

	public Date getPolicyIssuedDate() {
		return policyIssuedDate;
	}

	public void setPolicyIssuedDate(Date policyIssuedDate) {
		this.policyIssuedDate = policyIssuedDate;
	}

	public Date getUwDesicionDate() {
		return uwDesicionDate;
	}

	public void setUwDesicionDate(Date uwDesicionDate) {
		this.uwDesicionDate = uwDesicionDate;
	}

	public Date getFirstIssueDate() {
		return firstIssueDate;
	}

	public void setFirstIssueDate(Date firstIssueDate) {
		this.firstIssueDate = firstIssueDate;
	}

	public String getReasonCode() {
		return reasonCode;
	}

	public void setReasonCode(String reasonCode) {
		this.reasonCode = reasonCode;
	}

	public String getReffAgentCode() {
		return reffAgentCode;
	}

	public void setReffAgentCode(String reffAgentCode) {
		this.reffAgentCode = reffAgentCode;
	}

	public String getReffAgentName() {
		return reffAgentName;
	}

	public void setReffAgentName(String reffAgentName) {
		this.reffAgentName = reffAgentName;
	}

	public String getReffOfficeCode() {
		return reffOfficeCode;
	}

	public void setReffOfficeCode(String reffOfficeCode) {
		this.reffOfficeCode = reffOfficeCode;
	}

	public String getReffAreaCode() {
		return reffAreaCode;
	}

	public void setReffAreaCode(String reffAreaCode) {
		this.reffAreaCode = reffAreaCode;
	}

	public Date getEffectiveDate() {
		return effectiveDate;
	}

	public void setEffectiveDate(Date effectiveDate) {
		this.effectiveDate = effectiveDate;
	}

	public String getProposalNumber() {
		return proposalNumber;
	}

	public void setProposalNumber(String proposalNumber) {
		this.proposalNumber = proposalNumber;
	}

	public String getSyariahFlag() {
		return syariahFlag;
	}

	public void setSyariahFlag(String syariahFlag) {
		this.syariahFlag = syariahFlag;
	}

	public Date getTimeStamp() {
		return timeStamp;
	}

	public void setTimeStamp(Date timeStamp) {
		this.timeStamp = timeStamp;
	}

	public String getAgentCode() {
		return agentCode;
	}

	public void setAgentCode(String agentCode) {
		this.agentCode = agentCode;
	}

	public String getPolicyType() {
		return policyType;
	}

	public void setPolicyType(String policyType) {
		this.policyType = policyType;
	}

}